project:
  type: website
  output-dir: docs

website:
  title: "Serhii Tytiuk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    search: true
    background: "dark"

bibliography: [mylibrary.bib]
biblio-style: apalike
link-citations: yes
reference-location: margin

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

